travis:
  secure:
    BINSTAR_TOKEN: V30Y1N6/p+Uu7zRdI4QbAsHAEMw90m9ryVh8O4mUFlWVnGfCskM3Cq+kIa81sBAQLkBkiB64be9F0e/EH5yASzSmq2iKdr1vB48A0SKdmWuDHPfRSELb7pWBwOamOmH9gvGoWdrH5PQzLeNOElBXVF+kythxaNoBirIHY1sdhzZIcgCOTYick3EtTDyn+giA1Q2ddi4kEBzyY+XbpFVARX0xLA/BSJSMGwnvxsgWKkGh2gAKnTkf1Qmo/b4Q0J0S/iLiZryJQsT/xmXL4VIbtRIpETC73y+0XepsVEgG8zSPUqrP9ojPyMTp/4NqQ5C3m0XbX3LpI7Lwj7tUN+r4hMvc0fdnFhE3LT4zG3obMaBPdE75tnEjQk5ythOjL7EfmP4oENddD0oy17l+rXScpax6uCC06/p9pak1BPq12sW3jbRxQAIm2AIM+VDKpqDybdqojUBVmSugpEHy0tcrl+hnOYg5b1L4f5LTSAetTHJb5CE4bjibV6Dc0Td8h39FeMvBNffY3Yf9B5rvUV9jBlbZGw0GLuO1gWOMhkEL/f0uT/bD6J5HrX7/KaJgDmZgnLv7o1a0w/PyQlPP2WAVw/y/49R2KmZgGVQ/61SOojRs0I7FlTfIL9siZOQXE3DBDkkOjPJw0lzk6/JRV5OUT0o9zaapbBj8a0S6RX09Oiw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
