travis:
  secure:
    BINSTAR_TOKEN: X4PoBlUBVU0kvYW9c/DzplhvmvU13eLhGnvw1vshnaffKKv+zID/frjLStqXin7zAh1RpFFANnJU9Izh8wPQRW6xzpcTMa636xqmmsBkPQmTM8kxwTzm6t1BLWA2zcoiW0hcaEKeXIluH05uNtGuMll7fSLTX74Ar3qsJu7zbmtS0UUwo96A8wheMx17lBcY8LH1oRO4VeYaRBSabWe6Ys8cOS7nSx8f4FLQXHslEHaCxkII/yEGxJuiNn7kouO3zOE1NEMnzyXP3YNeRw2bt6m+4Keg3Rs9EeKK6eKUGzpv3ejwNOhCW+J//6XezEvGE4tj/RuphhBzBbA4BYduM1mv3OwwEttLpjMkN3Wa4LEfMRZl08nk2tJQ9beV5d26NrmfE523+NJm2Tw0GYx122jPAkmg2OJT6EudGaqjCC3hYV0ryVZ9X2P2zcz+S7Z5oh0B04uDT25jqTGF9pwjHbM/etOJBLtPE/MHLLlYxP6aVW0Vp8NLJ5ar7DGxIRZEMudGKUST5ODHRczrNO9GKhqXi474l2HSNPR0UCLzsBY6a9JayIlpzrlqnX2mebP+mgWXYoanRKYDuEVDaRnr5JejnKIoxwqMZhQjTbD5Bv4T5RgSr30F9Vz6CCerVTGHEZ7Yho+CXjHw7Hw6AoM81v3ZkHw8cow6UMHcGSKtrWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
