travis:
  secure:
    BINSTAR_TOKEN: ubT0mrf9KGCJ/ODZJTWzqG/3tm2Mizanbhyfzgp6oe+6Zx46qCovy7jeQE2IIBaCCte1ShIm/iFx9/mQxfczjjXgBNH3GVw13uAUgW+VlbDH4WWXQsEiJlzHUkF0o2+U7KziVl1jl2HA5uu5cy17xpdF+prrgg1In4FLRkAN1uiN8xMa1ijcvNF/T+c3jRoFI2/+Pg32i6GKotdmuI0d09uRI+qlFmBOIw0eQmnLvrB2Izmg/ahSXQOYlGWB1kLSUv/BlH48Y0asKvcgHXHXV+whkBz5oeqNEW38dxYRoUjlQfRWIoN9dx79brxyPGaMyZkgIFQ57LphZcnIKzQlYckJlxLjI0bcxyRXXJD0euMCKykVMU9+2DTg2bCgRXyXZy6gs2S3AlCTtWrnDLqUfFZntCKbKn/5/Oo/NKRA6Hc5zeptHSa1EZFfBJPk+MWgLnkP4RQoLxJOZ1dU9mYnVBhX5NPASrEphfQAnDCum6C71mBAmRVvSY9/+relSxX/thcUMaznjniRA7oZgqE48tzSmL+ivw1Ky/WXVqqLQf0UeIY3tGDdnRWNixQM5VwMR77mkstT1sZqaBmZA/tcrXk5mG0TzIxx/+WvAEaU5HUeqgQmDuuFWGRrNEnAt1XbVJbVYlSrP3AEFUzJnUZOtqVzta+PBYfBOEGxFHvSrlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
